# Generated by Django 2.2.5 on 2019-12-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discountsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
